### ISSUE TITLE
Overhaul README

### ISSUE THREAD

**Issue by vkoves** [IndigoBox/indigoBox-Website#10]
This was going to happen eventually. I made [a talk](https://www.youtube.com/watch?v=HnRRyKktyV4) in which I talked about how the indigoBox website README needed improving, and so we should set out to remedy it.

A few things we should have in the README:

- Features of the site
- Full tech stack including all plugins
- Installation Instructions (more important after completion of issue #6)
- Contribution Instructions (most likely saying if you have bugs or suggestions, open an issue!)

Does anyone else have ideas or suggestions for things to add to the README?

**Comment by SorenSpicknall** [comment]
The README was greatly improved at a point following the opening of this PR, but could still be a little more accessible if we expected external folks to ever care about it or fork the site. @vkoves, do you consider this to be done?

**Comment by vkoves** [comment]
I think the README has most of the info I suggested, so we're good for now.
