### ISSUE TITLE
Removal of Highlight on Project Pages

### ISSUE THREAD

**Issue by rjaltman** [IndigoBox/indigoBox-Website#15]
On the Projects landing, one has the ability to hover over images on panels to have them become lighter (so as to show that hover state). This is fine, and pretty well executed. However, the same transition is applied on the individual project pages themselves as well...but there isn't any other further interaction to be taken with the image. 

Therefore, should we remove the transition on the project pages? Furthermore, should we return it to its normal brightness on said pages?

**Comment by SorenSpicknall** [comment]
This has been remedied. Closing.
