### ISSUE TITLE
Mobile: Visit Site and Contributors clips off screen, forces horizontal scroll

### ISSUE THREAD

**Issue by rjaltman** [IndigoBox/indigoBox-Website#16]
The issue here is more with the latter problem, where most pages on the IndigoBox site have horizontal scroll disabled for mobile. On project pages, this should be no different, but the contributors list sometimes overflows on projects with many contributors (Carpe). Therefore, we need to devise a way of showing the contributors (I know that is an issue already) on mobile, but also make sure horizontal scroll is forced to be off here.

**Comment by vkoves** [comment]
This tied into #11 which has now been completed and closed. Check that out for how the project page looks now.
