### ISSUE TITLE
Repair "Is It Fresh?" Card on Project List Page

### ISSUE THREAD

**Issue by vkoves** [IndigoBox/indigoBox-Website#21]
Is It Fresh was released and is a functional site, so we should show it off on the site.

**Comment by rjaltman** [comment]
Thank you @AcademyInPeril for the recent PR #26 that added Is It Fresh to Projects! The only thing that is left now is to place an image on the card on the "Projects" page, probably just with the same image that is used on the individual project page for "Is It Fresh" itself. 

![image](https://user-images.githubusercontent.com/3650044/38287491-91998886-3790-11e8-8933-b5eb9496cb1f.png)

**Comment by vkoves** [comment]
Oh dear, this should not have passed review. That is on me for not checking the PR locally like I should have 😓

**Comment by SorenSpicknall** [comment]
This was solved awhile back, long enough ago that I cannot recall which PR remedied the issue. Closing.
