### ISSUE TITLE
Make Projects' Contributors Section Clearer

### ISSUE THREAD

**Issue by vkoves** [IndigoBox/indigoBox-Website#9]
On the indigoBox website, every project indicates who is working on the projects using circles with the profiles of the associated users, but there is no label indicating what this means. A simple label saying "Contributors", "Created By", or something of the sort would help make it clear to people unfamiliar with our site why certain people show up next to the links going off to certain projects. It might also make sense to separate the contributors into their own section entirely, especially since some projects may have a lot of contributors (like the website or Carpe).

See this screenshot for an example of how this looks right now, for reference:
![screenshot from 2017-01-02 04-12-21](https://cloud.githubusercontent.com/assets/3187531/21587405/ac149a54-d0a1-11e6-8dc5-83e6e2acd3dd.png)

**Comment by vkoves** [comment]
I worked on this when doing #11 and this section now looks like this:

![screenshot from 2017-02-19 10-55-46](https://cloud.githubusercontent.com/assets/3187531/23104365/0150ded6-f692-11e6-9bd2-e650ca9fb269.png)

Thoughts?

**Comment by SorenSpicknall** [comment]
This fulfilled the purpose of the issue. Closing.
